# Dependabot 설정 파일
# 자세한 정보: https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # npm 패키지 관리자 사용 (yarn, pnpm 등이 이에 해당)
    directory: "/" # package.json 위치
    schedule:
      interval: "daily" # 일간 업데이트 일정
      time: "09:00" # 오전 9시 (UTC)
    open-pull-requests-limit: 10 # 최대 PR 개수
    target-branch: "main" # PR을 보낼 대상 브랜치
    labels:
      - "dependencies" # PR에 적용할 라벨

    # 버전 업데이트 전략
    versioning-strategy: increase
